class StudentsController < ApplicationController
    def melvin
        @name= "melvin" 
        @eat="executive chef"
        @tv="Doctor Who"
        @bio="Throughout my whole life I have challenged the ideas and ideologies of others. I have left my mark in countless writing papers and assignments I have reached success at various levels throughout my years in the chicago public school system. I have encountered barriers and found opportunity where others see difficulty, one example of this was when I had a regional robotics competition but I was one of the few African american youth to participate in a STEM event abroad. Me and my dad booked a ticket to Southfield Michigan. A portion of Michigan that houses big industry buildings identifying with innovation and status. The Epicenter also houses many hotels and accommodations. During my visit I was able to take a breath from the city life and seek out my abilities as a student of Miles Davis Magnet Academy and soon to be Lindblom Math and Science Academy. During this transition period unto High School I devoted myself to being an honor roll student and forging my grade school life with high school life. Opportunities that I seek out add to my abilities to become successful. As a student I learned to value knowledge and what it brings, as a Chicagoan I learned to value equality, architecture, innovation and technology. Chicago has opened me to great endeavors one of them being the Common Ground Foundation. This organization has allowed me to connect with others and be myself while also structuring myself for a greater future. 
Recently I landed a summer internship via the Chicago Business Institute. I was given several options of work for the summer of the ones I was given I selected architecture and economics. I will be working downtown during my brief summer break and will possibly plan on vacationing to california to explore the scenery, the economical conjunctions and the colleges that are within California. Because that is my dream college location. But the work that led me to the current feats that I have reached is insurmountable. The days of stress, work, and inconvenience do not outweigh what I expect in my future. I have devoted 100% of myself to entrepreneurship and education. Being 16 makes this process easy but negative for my friendships and family. Their are the long nights of planning then there's the action of applying my abilities and becoming a learner of the workforce. I am motivated by the audaciousness of the future and the happiness I will bring to others through innovation and knowledge.
Silicon Valley is one of the keys to my door to success because they are the planners of the future and the catalyst for change. Everyone loves and uses technology and I feel as though I can use it to make the world a  better place, to effect, to change and to innovate. I read various books  that appeal to me such as the book House of Cards, 2001 A Space Odyssey and napoleon hill's think and grow rich. There are various things in my life that add to my ability to think at a greater level such as reading, attending Lindblom Math and Science academy, attending the Common Ground Foundation that allows me to reflect on myself. These things all add to my ability to mold myself into my future and assess and meet my goals. 
"
    end
    
end
